'use client';

/* eslint-disable @next/next/no-img-element -- Authenticated media is resized by our upload server. */

import { useEffect, useRef, useState } from 'react';
import type { PuzzleDefinition } from '@/lib/engine/puzzles/types';
import { actionClass, buttonClass, Field, inputClass, NumberField } from '../Fields';
import { adminRequest, requestId, type Asset, type OperationProps } from './client';

export default function MediaLibrary({ active, pending, run, notify, onCreatePuzzle }: Pick<OperationProps, 'pending' | 'run' | 'notify'> & { active: boolean; onCreatePuzzle: (puzzle: PuzzleDefinition) => void }) {
  const [assets, setAssets] = useState<Asset[]>([]); const [file, setFile] = useState<File | null>(null); const [error, setError] = useState('');
  const [selected, setSelected] = useState(''); const [rows, setRows] = useState(2); const [columns, setColumns] = useState(2);
  const uploadId = useRef('');
  const [deleteId, setDeleteId] = useState('');
  useEffect(() => {
    if (!active) return; let stopped = false;
    void adminRequest<{ media: Asset[] }>('/api/v2/admin/media').then(result => { if (!stopped) { setAssets(result.media); setError(''); } }).catch(failure => { if (!stopped) setError(failure instanceof Error ? failure.message : 'Could not load the media library.'); });
    return () => { stopped = true; };
  }, [active]);
  return <section className="space-y-6"><div><h2 className="text-2xl font-bold">Media library</h2><p className="mt-2 text-sm leading-6 text-slate-600">Upload images, audio, or short videos. Uploaded images are resized and compressed by the server.</p></div>{error && <p role="alert" className="rounded-lg bg-amber-50 p-3 text-sm text-amber-950">{error}</p>}
    <form className="space-y-4 rounded-xl border border-slate-200 bg-white p-5" onSubmit={event => { event.preventDefault(); if (!file) return; void run('upload', async () => { const form = new FormData(); form.set('file', file); form.set('requestId', uploadId.current || (uploadId.current = requestId())); const result = await adminRequest<{ media: Asset }>('/api/v2/admin/media', 'POST', form); setAssets(previous => [result.media, ...previous.filter(asset => asset.id !== result.media.id)]); setSelected(result.media.id); setFile(null); notify('Media uploaded. Its asset URL is ready to use in clues and hints.'); }); }}><Field label="Choose a file (up to 20 MB)"><input className={inputClass} type="file" accept="image/*,audio/mpeg,audio/mp4,audio/webm,audio/ogg,video/mp4,video/webm" disabled={Boolean(pending)} onChange={event => { setFile(event.target.files?.[0] || null); uploadId.current = requestId(); }} /></Field><button className={actionClass} disabled={Boolean(pending) || !file}>{pending === 'upload' ? 'Uploading…' : 'Upload media'}</button></form>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{assets.map(asset => <article key={asset.id} className="space-y-3 rounded-xl border border-slate-200 bg-white p-4">{asset.contentType.startsWith('image/') ? <>{/* eslint-disable-next-line @next/next/no-img-element */}<img src={asset.url} alt="Uploaded event asset" loading="lazy" className="h-40 w-full rounded-lg object-contain" /></> : asset.contentType.startsWith('audio/') ? <audio src={asset.url} controls preload="none" className="w-full" /> : <video src={asset.url} controls preload="metadata" className="h-40 w-full rounded-lg" />}<p className="text-xs text-slate-500">{asset.contentType} · {Math.ceil(asset.bytes / 1024)} KB</p><Field label="Asset URL"><input className={`${inputClass} font-mono text-xs`} readOnly value={asset.url} onFocus={event => event.target.select()} /></Field>{asset.contentType.startsWith('image/') && <button type="button" className={buttonClass} onClick={() => setSelected(asset.id)}>Use for jigsaw</button>}<button type="button" className={buttonClass} disabled={Boolean(pending)} onClick={() => setDeleteId(asset.id)}>Delete unused media…</button>{deleteId === asset.id && <div className="space-y-3 rounded-lg bg-amber-50 p-3 text-sm"><p>Delete this file? Media used by saved drafts or published versions cannot be deleted. Save any draft using this image before cleanup.</p><div className="flex flex-wrap gap-2"><button type="button" className={actionClass} disabled={Boolean(pending)} onClick={() => void run(`delete-media:${asset.id}`, async () => { await adminRequest('/api/v2/admin/media', 'DELETE', { mediaId: asset.id }); setAssets(previous => previous.filter(candidate => candidate.id !== asset.id)); setDeleteId(''); notify('Unused media deleted.'); })}>Confirm deletion</button><button type="button" className={buttonClass} onClick={() => setDeleteId('')}>Keep media</button></div></div>}</article>)}</div>
    {assets.some(asset => asset.id === selected && asset.contentType.startsWith('image/')) && <form className="space-y-4 rounded-xl border border-indigo-200 bg-indigo-50 p-5" onSubmit={event => { event.preventDefault(); void run('jigsaw', async () => { const result = await adminRequest<{ puzzle: PuzzleDefinition }>('/api/v2/admin/media', 'POST', { mediaId: selected, rows, columns }); onCreatePuzzle(result.puzzle); notify('The image was cut into tiles and added as a checkpoint in your current draft.'); }); }}><h3 className="text-lg font-bold">Make a jigsaw from this image</h3><div className="grid grid-cols-2 gap-4"><NumberField label="Tile rows" value={rows} min={2} max={6} onChange={setRows} /><NumberField label="Tile columns" value={columns} min={2} max={6} onChange={setColumns} /></div><button className={actionClass} disabled={Boolean(pending)}>Create tiles & add to draft</button></form>}
  </section>;
}
